### ISSUE TITLE
Fails to auto install cppyy

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/NWXCMake#4]
Trying to build ParallelZone with #3, a virtual environment based on system Python (version 3.10.6), and CMake 3.23.1 the configuration fails to build cppyy and I get the error:

```
[cmake] -- Found Python3: /home/ryan/workspaces/NWX/venv/bin/python3 (found version "3.10.6") found components: Interpreter 
[cmake] Traceback (most recent call last):
[cmake]   File "<string>", line 1, in <module>
[cmake] ModuleNotFoundError: No module named 'cppyy'
[cmake] Traceback (most recent call last):
[cmake]   File "<string>", line 1, in <module>
[cmake] ModuleNotFoundError: No module named 'cppyy'
[cmake] ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
[cmake] Traceback (most recent call last):
[cmake]   File "<string>", line 1, in <module>
[cmake] ModuleNotFoundError: No module named 'cppyy'
[cmake] Traceback (most recent call last):
[cmake]   File "<string>", line 1, in <module>
[cmake] ModuleNotFoundError: No module named 'cppyy'
[cmake] Python3: /home/ryan/workspaces/NWX/venv/bin/python3
[cmake] import output: 
[cmake] version output: 
[cmake] CMake Error at /home/ryan/workspaces/NWX/NWXCMake/cmake/FindCppyy.cmake:85 (message):
[cmake]   CMake could not install cppyy, try installing cppyy 3.0.0 manually.
[cmake] Call Stack (most recent call first):
[cmake]   /home/ryan/workspaces/NWX/NWXCMake/cmake/nwx_python_mods.cmake:49 (find_package)
[cmake]   CMakeLists.txt:102 (cppyy_make_python_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/home/ryan/workspaces/NWX/ParallelZone/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/ryan/workspaces/NWX/ParallelZone/build/CMakeFiles/CMakeError.log".
```

I am able to install cppyy 3.0.0 myself, so this issue is just about the attempt at the auto-install failing.

**Comment by keceli** [comment]
Do you get this error even when you explicitly set the Python executable in your toolchain, i.e. after adding `set(Python3_EXECUTABLE /path/to/venv/bin/python3)`?

**Comment by ryanmrichard** [comment]
@keceli Yes, I was explicitly setting the executable when I got the error.

**Comment by keceli** [comment]
I couldn't reproduce the issue, yet. Works for me with Python 3.8, `pip` 22.0.4 and Python 3.10.6, pip 22.0.2 on different machines. Are you using `VS Code` by any chance? There is an issue [here](https://github.com/microsoft/vscode-python/issues/14327) and a quick [fix](https://github.com/microsoft/vscode-python/issues/14327#issuecomment-757408341).
